# Generated by Django 5.1 on 2024-08-25 06:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fleet', models.CharField(max_length=255)),
                ('tail', models.CharField(max_length=255)),
                ('remark', models.TextField(blank=True, null=True)),
                ('required_action', models.TextField(blank=True, null=True)),
                ('owner', models.CharField(max_length=255)),
                ('logged', models.CharField(max_length=255)),
                ('duedate', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('level1', models.CharField(max_length=255)),
                ('level2', models.CharField(max_length=255)),
                ('level3', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
